### ISSUE TITLE
Suggestion: Ditch Monaco for a lighter code editor

### ISSUE THREAD

**Issue by uhidontkno** [z1g-project/Sodium#17]
Monaco is like Visual Studio Code, except it takes 10 seconds to load in a webpage and is 4mb which is very NOT lightweight. I would like you to use a different code highlighter for fields that you would like code highlighting in. 

I would suggest using CodeMirror as it is a lighter code editor than Monaco, My proxy [Immortal](https://github.com/ievade/Immortal) uses CodeMirror and it highlights just the same. 

PS: im going to work on something else so im not going to make a pr.

**Comment by Notplayingallday383** [comment]
Ay don’t worry i think i will prob ditch Monaco and implement the CSS editor beter since its been almost 2 entire versions since a update to it as for what editor you suggested codemirror so i might try that

**Comment by uhidontkno** [comment]
Also check out the PR i made which removes some UV metadata so it is harder for filters to automatically block all Sodium links, #18

**Comment by Notplayingallday383** [comment]
Prob just SEO tags should be changed and as for description I’m prob gonna make it just say something about internet censorship instead of proxy like you said lmao

**Comment by Notplayingallday383** [comment]
Merged into main thx

**Comment by Notplayingallday383** [comment]
Swapped to CodeBase and added some new functionality to it. and the loading went from 8mb to 1.2mb which is WAY beter and I like the new editor lol. Try it out https://beta.sodium-5h8.pages.dev/settings/css-editor/
