### ISSUE TITLE
Issue with sodium

### ISSUE THREAD

**Issue by idontplayminecraft** [z1g-project/Sodium#37]
![IMG_2681](https://github.com/z1g-project/Sodium/assets/145158192/24d19fd0-fe5f-480c-851a-1f19c47109ab)
Remember to read the [FAQ](https://beta.sodium-5h8.pages.dev/faq) before creating a issue
You can copy the debug info from the console and attach the console information below

**Webssite URL**

https://sodium.onrender.com/

**UserAgent**
Safari on school iPad

**Sodium Version**
Idk

**Attachments**
Add any console information or a screenshot of your error below

**Descriptiion of your Problem**
Breifly describe your problem

**Comment by Notplayingallday383** [comment]
Seems to just be a Bare issue. Ill make sure its not the backend Momentarily but you can solve this problem by self hosting sodium and changing the bares in the `ultra\ultra.config.js` and `dyn\dyn.config.js`

**Comment by Notplayingallday383** [comment]
Not enough information was specified
