### ISSUE TITLE
Feature request!

### ISSUE THREAD

**Issue by mjwg** [z1g-project/Sodium#40]
**Webssite URL**
N/A

**UserAgent**
N/A

**Sodium Version**
Example: 1.3.7 (LTS)

You should add a local one, where it uses a public bare server and is just an html file in your downloads

**Comment by mjwg** [comment]
Like, static but not complicated

**Comment by Riftriot** [comment]
Service workers require SSL certificates/HTTPS, as such that won't work

**Comment by mjwg** [comment]
Ohhhhhh, i see now

**Comment by IncognitoTGT** [comment]
You can actually put the proxy on a bare host like GitHub or CF pages and change the URL, but I'm not gonna cover that here.
