### ISSUE TITLE
Roblox restricted in current region

### ISSUE THREAD

**Issue by hejagithub** [z1g-project/Sodium#61]
**Website URL**
[https://www.aliheja.website/](https://www.aliheja.website/)

**UserAgent**
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0

**Sodium Version**
v2.0.0

**Description of my Problem**
Roblox is restricted on now.gg because it's not avaliable in my region. I've ran Aptoide and installed Roblox from there as a temporary fix for now. Any suggestions on how to fix?

**Comment by yu6x** [comment]
now.gg also doesn't like proxies connecting to their website because they want more people going to their main website so as of right now there is no way to fix this.

**Comment by hejagithub** [comment]
> now.gg also doesn't like proxies connecting to their website because they want more people going to their main website so as of right now there is no way to fix this.

Wouldn't it say like "VPN/Proxy detected" then?

**Comment by Notplayingallday383** [comment]
This isn’t really a problem with sodium itself but rather ultraviolet site problems with ultraviolet v2 or its blocked on the bare server your using. If it’s one of those problems, don’t worry I’m working on an update currently that implements ultraviolet v3 and wisp stuff soon. Expect it to be released around may. PS: Don’t make a issue to UV or Bare about this as it’s not their problem

**Comment by hejagithub** [comment]
> This isn’t really a problem with sodium itself but rather ultraviolet site problems with ultraviolet v2 or its blocked on the bare server your using. If it’s one of those problems, don’t worry I’m working on an update currently that implements ultraviolet v3 and wisp stuff soon. Expect it to be released around may. PS: Don’t make an issue to UV or Bare about this as it’s not their problem. I will close this issue once the update drops

Could you use Dynamic instead to fix the issue?

**Comment by 1coolmatt8083** [comment]
hey guys im currently trying to figure out how to play roblox on my cromebook and since my crome book has lightspeed agent on it. it hasent been easy. if u guys could help me find somthin plz let me no, thx!!

**Comment by IncognitoTGT** [comment]
tf
stop commenting on closed issues
