### ISSUE TITLE
Now.gg detects the main sodium website

### ISSUE THREAD

**Issue by hejagithub** [z1g-project/Sodium#62]
Website URL
[https://sodium-5h8.pages.dev/](https://sodium-5h8.pages.dev/)

UserAgent
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0

Sodium Version
v2.0.0

Description of my Problem
Now.gg detects website as proxy. I have gotten now.gg to not detect on my own website tho.

**Comment by Notplayingallday383** [comment]
This is just public wisp/bare servers being detected
