### ISSUE TITLE
Lots of games saying 404

### ISSUE THREAD

**Issue by hejagithub** [z1g-project/Sodium#63]
Website URL
[https://sodium-5h8.pages.dev/](https://sodium-5h8.pages.dev/) [https://www.aliheja.website/](https://www.aliheja.website/)

UserAgent
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0

Sodium Version
v2.0.0

Description of my Problem
Many of the default games including but not limited to Among Us, Baldi's Basics, SM64 and BItlife currently say "404: Not Found" when you try to use them.

**Comment by IncognitoTGT** [comment]
what
